apiVersion: v1
kind: Service
metadata:
  name: my-app
  namespace: apps
  labels:
    app: my-app
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 9009
  selector:
    app: my-app
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  namespace: apps
  labels: 
    app: my-app
spec:
 replicas: 1
 selector:
   matchLabels:
     app: my-app
 template:
   metadata:
     labels:
       app: my-app
   spec:
     containers:
     - name: my-app
       image: diegob/app01:1
       imagePullPolicy: Always 
       env:
         - name: HOST
           value: "my-db"
         - name: LPORT
           value: "9009"
       ports: 
        - containerPort: 9009
          protocol: TCP
