apiVersion: v1
kind: Service
metadata:
  labels:
    app: my-db
  name: my-db
  namespace: apps
spec:
  ports:
    - port: 5432
      protocol: TCP
  selector:
    app: my-db
  type: ClusterIP 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-db
  namespace: apps
  labels: 
    app: my-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-db
  template:
    metadata:
      labels:
        app: my-db
    spec:
      containers:
      - name: my-db
        image: postgres:13.5
        env:
          - name: POSTGRES_PASSWORD
            value: "diego00"
        ports: 
        - containerPort: 5432
          protocol: TCP